version: '3'
services:
  nginx:
    image: 123456789123.dkr.ecr.ap-northeast-1.amazonaws.com/sample-nginx
    ports:
      - "80:80"
    volumes:
      - data1:/data1
  fluent:
    image: 123456789123.dkr.ecr.ap-northeast-1.amazonaws.com/sample-fluent
    volumes:
      - data1:/data1
    logging:
      driver: awslogs
      options:
        awslogs-group: tutorial
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: nginx-fluent
volumes:
  data1:
